services:
  app:
    image: jc21/nginx-proxy-manager:2.15.1
    container_name: nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "81:81"

    environment:
      TZ: Asia/Kolkata

      DB_POSTGRES_HOST: db
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_USER: npm
      DB_POSTGRES_PASSWORD: npmpass
      DB_POSTGRES_NAME: npm

      # DISABLE_IPV6: "true"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    depends_on:
      - db

    networks:
      - proxy-network

  db:
    image: postgres:17
    container_name: nginx-proxy-manager-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: npm
      POSTGRES_PASSWORD: npmpass
      POSTGRES_DB: npm

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
